services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Shopsys\ShopBundle\Form\:
      resource: '../../Form/'

  Shopsys\ShopBundle\Form\Admin\ArticleFormTypeExtension:
    tags:
      - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Article\ArticleFormType }
